// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAekLM0V5OihOe8IkriTnn1VTApY5RgbBA',
    appId: '1:1091114693150:web:a7ca9a7f4ae4a77976740f',
    messagingSenderId: '1091114693150',
    projectId: 'learning-app-007-91086',
    authDomain: 'learning-app-007-91086.firebaseapp.com',
    storageBucket: 'learning-app-007-91086.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2a-jPktvIn1ZI6Q9CXWsRW3eQt5dsPA',
    appId: '1:1091114693150:android:e0fb4933f6ef1ed776740f',
    messagingSenderId: '1091114693150',
    projectId: 'learning-app-007-91086',
    storageBucket: 'learning-app-007-91086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRfvRO7F1zTWgR8Xeeb3qxd-8bbY7avI',
    appId: '1:1091114693150:ios:5566f212deeba49476740f',
    messagingSenderId: '1091114693150',
    projectId: 'learning-app-007-91086',
    storageBucket: 'learning-app-007-91086.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRfvRO7F1zTWgR8Xeeb3qxd-8bbY7avI',
    appId: '1:1091114693150:ios:5566f212deeba49476740f',
    messagingSenderId: '1091114693150',
    projectId: 'learning-app-007-91086',
    storageBucket: 'learning-app-007-91086.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAekLM0V5OihOe8IkriTnn1VTApY5RgbBA',
    appId: '1:1091114693150:web:6d73deae63ee188b76740f',
    messagingSenderId: '1091114693150',
    projectId: 'learning-app-007-91086',
    authDomain: 'learning-app-007-91086.firebaseapp.com',
    storageBucket: 'learning-app-007-91086.firebasestorage.app',
  );
}
